### ISSUE TITLE
Is there a Backslash you pressed accidentally before WP_Query text ?

### ISSUE THREAD

**Issue by kenny90263** [Sandy-Garrido/wordpress-ajax-pagination-sticky-pinned#1]
`$pinned_posts = new \WP_Query($pinned_args);`

Is there a **Backslash** you pressed accidentally before WP_Query text ?

**Comment by sandy-garrido** [comment]
> `$pinned_posts = new \WP_Query($pinned_args);`
> 
> Is there a **Backslash** you pressed accidentally before WP_Query text ?

Hi @kenny90263 
It's not accidental, although official docs do not use this backslash, it is a legacy thing, some people use it some people don't. It does look like it's not required though, I can't confirm :).
